### ISSUE TITLE
The pytorch_checkpoints rgb_imagenet.pkl is not correct? 

### ISSUE THREAD

**Issue by yyuanad** [rimchang/kinetics-i3d-Pytorch#1]
Hi, it seems that the rgb_imagenet.pkl is not correct. The dimensions in the RGB-I3D model are torch.Size([64, 3, 7, 7, 7]) but the dimensions in the checkpoint are torch.Size([64, 2, 7, 7, 7]).

**Comment by rimchang** [comment]
could you explain where find it?

I cannot find dimensions 2

import torch
rgb_imagenet = torch.load("rgb_imagenet.pkl")
flow_imagenet = torch.load("flow_imagenet.pkl")
rgb_scratch = torch.load("rgb_scratch.pkl")
flow_scratch = torch.load("flow_scratch.pkl")

print(rgb_imagenet['features.0.conv.weight'].shape)
print(flow_imagenet['features.0.conv.weight'].shape)
print(rgb_scratch['features.0.conv.weight'].shape)
print(flow_scratch['features.0.conv.weight'].shape)

output

torch.Size([64, 3, 7, 7, 7])
torch.Size([64, 2, 7, 7, 7])
torch.Size([64, 3, 7, 7, 7])
torch.Size([64, 2, 7, 7, 7])
