### ISSUE TITLE
dropout_keep_prob in I3D should be set to 0

### ISSUE THREAD

**Issue by zijunwei** [rimchang/kinetics-i3d-Pytorch#2]
According to the documentation and my test results, the parameter dropout_keep_prob setting to 1 in https://github.com/rimchang/kinetics-i3d-Pytorch/blob/master/model/I3D_Pytorch.py means an element will be zeroed at prob to 1. this will create uniform results in training.

**Comment by rimchang** [comment]
thank you for telling me.
